// File generated by FlutterFire CLI — placeholder.
// Rulează `flutterfire configure` ca să înlocuiești cheile cu valorile reale.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// ID-urile de aplicație sunt cele din `firebase.json` (proiect `rewire-32a9d`).
/// `apiKey` trebuie regenerat local — fără el, aplicația pornește totuși offline.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions nu sunt configurate pentru Linux. '
          'Rulează flutterfire configure sau folosește modul offline.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions nu sunt configurate pentru această platformă.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_WITH_WEB_API_KEY',
    appId: '1:49983814244:web:69297241dbb65ed5a37d71',
    messagingSenderId: '49983814244',
    projectId: 'rewire-32a9d',
    authDomain: 'rewire-32a9d.firebaseapp.com',
    storageBucket: 'rewire-32a9d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_WITH_ANDROID_API_KEY',
    appId: '1:49983814244:android:86f94607d4530941a37d71',
    messagingSenderId: '49983814244',
    projectId: 'rewire-32a9d',
    storageBucket: 'rewire-32a9d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_WITH_IOS_API_KEY',
    appId: '1:49983814244:ios:e11f59f1e90fbeb1a37d71',
    messagingSenderId: '49983814244',
    projectId: 'rewire-32a9d',
    storageBucket: 'rewire-32a9d.firebasestorage.app',
    iosBundleId: 'com.hbrnm.rewire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REPLACE_WITH_IOS_API_KEY',
    appId: '1:49983814244:ios:e11f59f1e90fbeb1a37d71',
    messagingSenderId: '49983814244',
    projectId: 'rewire-32a9d',
    storageBucket: 'rewire-32a9d.firebasestorage.app',
    iosBundleId: 'com.hbrnm.rewire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'REPLACE_WITH_WEB_API_KEY',
    appId: '1:49983814244:web:ea4bb7caa9acb838a37d71',
    messagingSenderId: '49983814244',
    projectId: 'rewire-32a9d',
    authDomain: 'rewire-32a9d.firebaseapp.com',
    storageBucket: 'rewire-32a9d.firebasestorage.app',
  );
}
